name:                plainbudgetting
version:             0.1.0.0
github:              "Triagle/plainbudgetting-hs"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.adoc
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Triagle/plainbudgetting-hs#readme>

dependencies:
- base >= 4.7 && < 5
- classy-prelude
- optparse-applicative
- parsec
- dlist
- transformers
- bytestring
- cassava
- vector
- text

default-extensions: NoImplicitPrelude OverloadedStrings

library:
  source-dirs: src

executables:
  plbudget:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - plainbudgetting

tests:
  plainbudgetting-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - plainbudgetting
